### ISSUE TITLE
CPU is being highly used.

### ISSUE THREAD

**Issue by chapig** [aviks/GameZero.jl#11]
First of all, I apologize if this is not an issue. 

I noticed that whenever the actor is running, the cpu starts being used and it reaches 25% which causes a drop in the framerates. I am not sure if changing the image of the actor causes this. I tried turning off `animations()` to check if the other animations in the environment like the platform and the plants were causing it. It was not that. So my thoughts noticing that pattern was that looping and changing images in a fast way, causes this. I am not sure if this is normal or maybe it is an issue. Thank you.

The images are here.
[images.zip](https://github.com/aviks/GameZero.jl/files/5144814/images.zip)

This is how the game looks.
The assets are not mine. Author: [https://maaot.itch.io/mossy-cavern](url)
![Screenshot_1](https://user-images.githubusercontent.com/46666572/91629632-acb40080-e998-11ea-9472-915c372d2a6b.png)

```
function update(g::Game)

    bring_back()
    gravity()
    animations()
    #####################
    #WALKING AND RUNNING#
    #####################

    global STEP, IDLE, VELOCITY, LOOKING_AT

    if g.keyboard.LCTRL && g.keyboard.D #RUNNING TO THE RIGHT SIDE
        LOOKING_AT = 0
        VELOCITY = 0
        if VELOCITY < 50
            VELOCITY += 1
        end
        STEP += 1
        witch.image = "wr$(STEP).png"
        witch.x += 3
        witch.image = "wr$(STEP).png"
        if STEP == 18
            STEP = 1
        end

    elseif g.keyboard.LCTRL && g.keyboard.A #RUNNING TO THE LEFT SIDE
        LOOKING_AT = 1
        VELOCITY = 0
        if VELOCITY < 5
            VELOCITY += 1
        end
        STEP += 1
        witch.image = "wr$(STEP).png"
        witch.x -= 3
        witch.image = "wl$(STEP).png"
        if STEP == 18
            STEP = 1
        end

    elseif g.keyboard.A 

        LOOKING_AT = 1
        VELOCITY += 2
        STEP += 1
        witch.image = "wl$(STEP).png"
        witch.x -= 2
        if STEP == 18
            STEP = 1
        end

    elseif g.keyboard.D
        LOOKING_AT = 0
        VELOCITY += 2
        STEP += 1
        witch.image = "wr$(STEP).png"
        witch.x += 2
        if STEP == 18
            STEP = 1
        end
    else

        ################
        #IDLE ANIMATION#
        ################
        
        LOOKING_AT = 2 #LOOKING AT CENTER

        IDLE += 0.35

        witch.image = "i$(round(Int, IDLE)).png"

        if round(Int, IDLE) == 18
            IDLE = 1
        end
        VELOCITY = 0

    end
end
```

**Comment by aviks** [comment]
I don't think there is anything actionable here.This package is not meant to support very high performance games, but also our overhead on top of SDL2 is not particularly high. So I feel this is OS-ish for now.
