### ISSUE TITLE
Actors vanish after some time...

### ISSUE THREAD

**Issue by dustyirwin** [aviks/GameZero.jl#15]
I'm having some problems with the actors that I load into a game. 

After some time (I haven't yet been able to determine a rhyme or reason yet, but usually after there are a few sprites in play or after 10~15 seconds) the actors all disappear and I'm left with an empty screen. I can still hear music and sounds being activated, just no visuals. Closing the game and reloading usually works (sometime it just hangs, forcing a Julia reboot) and it will draw the actors again until they disappear again. 

Has anyone else had a similar issue?

**Comment by aviks** [comment]
That's really weird, I've never seen anything like it. What platform are you in? Maybe put some logging in the game loop to see what is happening?

**Comment by dustyirwin** [comment]
This should be patched in https://github.com/aviks/GameZero.jl/pull/17

**Comment by dustyirwin** [comment]
This should be patched in https://github.com/aviks/GameZero.jl/pull/17
