### ISSUE TITLE
What's the best way to determine if an `Actor` has been clicked?

### ISSUE THREAD

**Issue by xiaodaigh** [aviks/GameZero.jl#27]

**Comment by aviks** [comment]
In the on_mouse_click handler, check if 

`(a.left < click_x <a.right) && (a.top < click_y < a.bottom)` 

where `a` is the `Actor` and `click_x` and `click_y` are the click coordinates. 

Something along these lines.....

**Comment by aviks** [comment]
To be clear, if your actor has transperancies, and you want to account for that, I don't think there is a way to do that. It might be possible to use Images.jl to understand the color of the pixel etc.  The code above considers the actor to be a rectangle.
