### ISSUE TITLE
`actor.right` is incorrect ?

### ISSUE THREAD

**Issue by MarcMush** [aviks/GameZero.jl#36]
While trying out [Flappy Bird](https://github.com/SquidSinker/GZExamples/tree/master/Flappy%20bird) and tinkering with it, I stumbled accross some strange things.

we have `actor.right < actor.left`:
```
(pipe_top.right, pipe_top.left) = (228, 328)
(pipe_top.right, pipe_top.left) = (225, 325)
(pipe_top.right, pipe_top.left) = (222, 322)
```

it seems like `right` is computed as `left - width`. shouldn't it be `left + width` or am I missing something ?

https://github.com/aviks/GameZero.jl/blob/938cc41b34f8ffd9c453ddb9fcd3da8ea67adf4a/src/screen.jl#L87-L90

EDIT: same thing for `bottom`

**Comment by aviks** [comment]
Hmm.. I thought I'd tested this -- will check.
