### ISSUE TITLE
Crash on `rungame`

### ISSUE THREAD

**Issue by mbaz** [aviks/GameZero.jl#40]
```
julia> rungame("basic.jl")
libGL error: MESA-LOADER: failed to open iris: /home/miguel/bin/julia-1.6.2/bin/../lib/julia/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/dri/iris_dri.so) (search paths /usr/lib/dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open iris: /home/miguel/bin/julia-1.6.2/bin/../lib/julia/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/dri/iris_dri.so) (search paths /usr/lib/dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast: /home/miguel/bin/julia-1.6.2/bin/../lib/julia/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/dri/swrast_dri.so) (search paths /usr/lib/dri)
libGL error: failed to load driver: swrast
X Error:  BadValue
  Request Major code 152 (GLX)
  Request Minor code 3 ()
  Value 0x0
  Error Serial #103
  Current Serial #104
~ $
```

* Arch Linux, up to date as of today.
* Intel IceLake i5 with Iris graphics.
* Julia 1.6.2

This looks to me like an incompatibility between Julia's bundled libstdc++ and my system drivers. Is there a way to make GameZero use my system's libstdc++?

**Comment by aviks** [comment]
While I'm loath to summon  @giordano or @staticfloat to a random project's isues, I have a feeling they will know the answer.

**Comment by giordano** [comment]
Sigh.  That's basically https://github.com/JuliaLang/julia/issues/34276.

**Comment by aviks** [comment]
Thanks Mose. I'll close this here, since I don't think we can work around any of this here.

**Comment by staticfloat** [comment]
Users can work around it by copying their own libstdc++ from their system directory over the one provided by Julia. This is harmless as long as the one you’re overwriting with is newer.
