### ISSUE TITLE
Make GameZero types better and more extensible

### ISSUE THREAD

**Issue by DhruvaSambrani** [aviks/GameZero.jl#56]
Right now, all Game objects are concrete. However, it may be worthwhile to abstract out things right now.
Primarily, `Game` and `Actor` must be subtypes of `AbstractGame` and `AbstractActor`, which themselves can be concretised to `Actor` and `Game`. Functions which can be abstracted should be.

**Comment by scottbigbrain** [comment]
There are a lot of functions that probably need to be abstracted, but what would be the reason for abstracting `Game` or `Actor`?
