### ISSUE TITLE
There is no description on how to run a game

### ISSUE THREAD

**Issue by arnaudmgh** [aviks/GameZero.jl#6]
There is a description only in the other package of game examples, but it should be here as well:

pkg> add https://github.com/aviks/GameZero.jl
julia> using GameZero
julia> GameZero.rungame("C:\\path\\to\\GZExamples\\Spaceship\\Spaceship.jl")

**Comment by xiaodaigh** [comment]
can close this?

**Comment by arnaudmgh** [comment]
... is it a question for me?
To clarify, my suggestion is adding a `readme.md` with the instructions on how to run the example, as there are no instructions in https://github.com/aviks/GameZero.jl/tree/master/example/BasicGame

**Comment by ianlundeen** [comment]
That method of runnning a game does not seem to work for me

**Comment by aviks** [comment]
@arnaudmgh  I've added this to the README. https://github.com/aviks/GameZero.jl#running-games. The [docs](https://juliahub.com/docs/GameZero/tTDGf/) also has more info. I'll close this. 

@ianlundeen can you tell me what error you see? Maybe open a new issue if you still have trouble?
