### ISSUE TITLE
Unicode Chinese Characters (ttf) are not being shown 

### ISSUE THREAD

**Issue by Shum88** [aviks/GameZero.jl#66]
if gameover == false
        display = "分數(Score) = $score"
    else
        display = "GAME OVER! Final Score = $score"
        #play again instructions
        replay = TextActor("Click to play Again,  點擊...再玩", sDspFont; font_size = 26, color = Int[0, 0, 0, 255])
        replay.pos = (135, 390)
        draw(replay)
    end

above Chinese Character are not being shown 
![title_01](https://user-images.githubusercontent.com/3876605/227614100-772b6441-c858-4330-a601-9ec5415dcee5.jpg)

**Comment by Shum88** [comment]
sDspFont::String = "wt009"

**Comment by aviks** [comment]
Some research suggests that the solution here is to use `TTF_RenderUTF8_Blended` rather than `TTF_RenderText_Blended` as we do currently in `TextActor`

**Comment by Shum88** [comment]
#sf = SDL2.TTF_RenderText_Blended(font, text, SDL2.Color(color...))
    sf = SDL2.TTF_RenderUTF8_Blended(font, text, SDL2.Color(color...))

After modified the actor.jl:TextSctor() function as above ...
Chinese Characters can be shown correctly
![SnakeZero_01](https://user-images.githubusercontent.com/3876605/227696198-ed56d555-17b9-4b9c-bc44-a091174cd439.jpg)
![SnakeZero_02](https://user-images.githubusercontent.com/3876605/227696210-5405ce0e-b506-445c-a3d4-3f0fb7b6c3ef.jpg)

**Comment by Shum88** [comment]
Hi Aviks,

Following your suggestion ...
Chinese Characters can be shown correctly

Thanks  again !

Shum

________________________________
寄件者: Avik Sengupta ***@***.***>
寄件日期: 2023年3月25日 3:10
收件者: aviks/GameZero.jl ***@***.***>
副本: Shum ***@***.***>; Author ***@***.***>
主旨: Re: [aviks/GameZero.jl] Unicode Chinese Characters (ttf) are not being shown (Issue #66)


Some research suggests that the solution here is to use TTF_RenderUTF8_Blended rather than TTF_RenderText_Blended as we do currently in TextActor

**Comment by aviks** [comment]
Thank you for confirming. We do need to fix this in this project as well.
