### ISSUE TITLE
Control Render

### ISSUE THREAD

**Issue by alerem18** [aviks/GameZero.jl#70]
is it possible to control render?
like user decide when to draw objects and when not to draw objects(for faster execution sometimes we don't need rendering, like while training a deep learning agent)

**Comment by aviks** [comment]
You can control whatever you do in the `draw()` function that you write. The function is called every frame, but you don't have to do the same thing every frame. For example, you can set a global counter and then draw an object every 10 frames. Or whatever complex scheme you can think of.
