### ISSUE TITLE
UndefRefError: access to undefined reference

### ISSUE THREAD

**Issue by lindas35** [aviks/GameZero.jl#72]
txt = TextActor("Text", "moonhouse")
i'm getting this error recently while i didn't have it before, i have fonts folder and moonhouse.ttf font inside it but i'm getting this error

ERROR: UndefRefError: access to undefined reference
Stacktrace:
 [1] getproperty
   @ .\Base.jl:38 [inlined]
 [2] getindex
   @ .\refvalue.jl:56 [inlined]
 [3] file_path(name::String, subdir::Symbol)
   @ GameZero C:\Users\Administrator\.julia\packages\GameZero\q74y7\src\resources.jl:46
 [4] TextActor(text::String, font_name::String; font_size::Int64, color::Vector{Int64}, kv::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ GameZero C:\Users\Administrator\.julia\packages\GameZero\q74y7\src\actor.jl:34
 [5] TextActor(text::String, font_name::String)
   @ GameZero C:\Users\Administrator\.julia\packages\GameZero\q74y7\src\actor.jl:33
 [6] top-level scope
   @ c:\Users\Administrator\Desktop\julia\test_snake.jl:30

**Comment by aviks** [comment]
Hi @lindas35 did you manage to get over this issue? Would be nice to document what you did, to help folks hitting similar issues in the future.

**Comment by Jesse370** [comment]
I'm having this issue too just trying to compile the basic game in Visual Studio Code. The strange part is that running the game using rungame in the command line works perfectly fine. How did you fix this issue?

![resources jl - BasicGame - Visual Studio Code 4_26_2023 5_23_35 PM](https://user-images.githubusercontent.com/70352076/234708631-3857ad33-15a0-4a4b-8613-fe6e747bd363.png)

**Comment by aviks** [comment]
@Jesse370 GameZero is designed to be run via the `rungame` method. That sets up the environment that the code requires. You will not be able to run the julia file directly.

**Comment by Jesse370** [comment]
Ah ok, so in order to make sure everything has compiled correctly I have to run the game using the rungame method from the command line each time? There isn't a way for me to put the rungame method in the script itself?

**Comment by aviks** [comment]
> There isn't a way for me to put the rungame method in the script itself?

Yes, that is the case currently, that's how it's designed. I want to change that in the future, but that has turned out to be more difficult that I imagined.

**Comment by Jesse370** [comment]
Ah ok, I saw something on the documentation about that and wasn't sure if I was doing something wrong or not. Thank you for the help!

**Comment by aviks** [comment]
There was a [PR ](https://github.com/aviks/GameZero.jl/pull/38)to make this change but unfortunately it still doesn't work too well.
