### ISSUE TITLE
use `angle` to draw actor

### ISSUE THREAD

**Issue by aviks** [aviks/GameZero.jl#8]
We store the `angle` for an actor, but do not use it transform the image during draw.

**Comment by dustyirwin** [comment]
Is this also true for the `scale` attribute? I've tried adjusting both on my Actors, to no effect.

**Comment by aviks** [comment]
Ah, yes, `scale` is also is not implemented yet.

**Comment by dustyirwin** [comment]
Hi aviks, I've opened a pull request implementing the angle and scale attributes. Cheers!

**Comment by aviks** [comment]
Fixed by #14
